### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Xenimus/project6#1]
When I submit the form, I expect to see my changes saved in the form, as specified in the project (`every form field should always show the current parameters`). You can do [something like this](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) to make sure the current params are reflected in the form.

Let me know when this is updated and I'll take another look.

**Comment by Xenimus** [comment]
I updated the app to show the current parameters in the form fields

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
